Update uniform.config.ts - Disable locales since it's empty
The npm run uniform:push on an empty project and a fresh code pull gives an error about locales, since there are no locales in the codebase but now Uniform always sets a default locale of en-US. Excluding locales in the Uniform config allows the CLI push command to run successfully.

Error: Error: Sync source (files in uniform-data/locale) is empty and mode is mirror. This would cause deletion of everything in the target (Uniform API), and most likely indicates an error in source definition.